# Generated by Django 5.1 on 2024-09-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_alter_teacher_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_months', models.IntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
