# Generated by Django 5.1 on 2024-09-02 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='graduate',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Active', 'Active'), ('Graduate', 'Graduate')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.student')),
            ],
        ),
    ]
