# Generated by Django 5.1 on 2024-09-03 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0007_remove_student_graduate_student_status_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='course',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='student_class',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashapp.glass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_paid',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reference_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('registration', 'Registration Fee'), ('monthly', 'Monthly Fee'), ('certificate', 'Certificate Fee')], max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.transaction')),
            ],
        ),
    ]
