# Generated by Django 5.1 on 2024-09-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-username'], 'permissions': [('manage_role_groups', 'Can Add Or Delete Role From The Group'), ('remove_role_from_group', 'Can Remove Role From Group'), ('assign_user_to_group', 'Can Assign User To Group'), ('role_report', 'Can See Roles Report'), ('view_dashboard', 'Can view dashboard')]},
        ),
    ]
