# Generated by Django 5.1 on 2024-09-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_audittrials_errorlogs_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
